baseURL = "https://holyfamilyseattle.github.io/"
languageCode = "en-us"
title = "Holy Family Syro Malabar Catholic Mission"
theme = "alpha-church"

[markup.goldmark.renderer]
  unsafe = true

#This theme can generate a multi-level menu.
#Use weight= to specify the order of menu items, and parent= to create a submenu item.
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
     name = "About Us"
     url = "/about"
     weight = 2

  [[menu.main]]
     name = "About"
     url = "/about"
     parent = "About Us"
     weight = 1

  [[menu.main]]
    name = "Chicago Diocese"
    url = "https://www.stthomasdiocese.org/"
    parent = "About Us"
    weight = 2

  [[menu.main]]
    name = "ParishOnNet"
    url = "/parish-on-net"
    parent = "About Us"
    weight = 3
  
  [[menu.main]]
    name = "Events"
    url = "/events"
    weight = 3
    
  [[menu.main]]
    name = "Faith Formation"
    url = "/about-ccd"
    weight = 3

  [[menu.main]]
    name = "About CCD"
    url = "/about-ccd"
    parent = "Faith Formation"
    weight = 1

  [[menu.main]]
    name = "CCD Calendar"
    url = "/calendar"
    parent = "Faith Formation"
    weight = 2

  [[menu.main]]
    name = "CCD Team"
    url = "/ccd-team"
    parent = "Faith Formation"
    weight = 3  

  [[menu.main]]
    name = "CCD Guidelines"
    url = "/ccd-guidelines"
    parent = "Faith Formation"
    weight = 4

  [[menu.main]]
    name = "CCD Associations"
    url = "/ccd-associations"
    parent = "Faith Formation"
    weight = 5

  [[menu.main]]
    name = "CCD Theme 2024-25"
    url = "/ccd-theme-2024-2025"
    parent = "Faith Formation"
    weight = 6

  [[menu.main]]
    name = "CCD Theme 2023-24"
    url = "/ccd-theme-2023-2024"
    parent = "CCD Theme 2024-25"
    weight = 6

  [[menu.main]]
    name = "Resources"
    parent = "Faith Formation"
    weight = 7

  [[menu.main]]
    name = "CCD Registration"
    url = "https://forms.gle/yACwh84g6i22LJWYA"
    parent = "Resources"
    weight = 1

  [[menu.main]]
    name = "CCD Handbook"
    url = "https://drive.google.com/file/d/1g6-FvRjDButCrnB8MEN_gZmWBt-YxTNJ/view"
    parent = "Resources"
    weight = 2

  [[menu.main]]
    name = "Online Forms"
    url = "/online-forms"
    weight = 4

  [[menu.main]]
    name = "Donate"
    url = "/donation"
    weight = 5

  [[menu.main]]
    name = "Contact Us"
    url = "/contact"
    weight = 6

  [[menu.main]]
    name = "Contact"
    url = "/contact"
    parent = "Contact Us"
    weight = 1

  [[menu.main]]
    name = "Leaders"
    url = "/leaders"
    parent = "Contact Us"
    weight = 2


# Paramaters for the whole site
[params]
  title = "Holy Family Syro Malabar Catholic Mission"
  subtitle = "(Syro Malabar Catholic Eparchy of Chicago)"
  author = "Ajith Cherukad Jose"
  keywords = ["hugo"]
  languageCode = "en" # For accessibility this needs to be set. You can find all language codes at https://www.w3schools.com/tags/ref_language_codes.asp
  bible_popups = "faithlife" #faithlife, blb
  bible_version = "CSB" #HCSB, NIV, NLT, ESV, etc.
  instant_page = true

  customCSS = ["example.css"]

  [params.favicon]
    sml = "/img/logo.png"
    med = "/img/logo.png"
    #lge = "example96.png"

  [params.banner]
    image = "img/banner.jpg"

  [params.nav]
    image = "/img/logo.png"

  [[params.links]]
    service = "Facebook"
    icon = "fa-facebook"
    icon_pack = "fab"
    link = "https://www.facebook.com/groups/SeattleSyroMalabar"

  [params.footer]
    copyright = ["[CC0 (public domain)](//creativecommons.org/publicdomain/zero/1.0/)",
                 "Design: [HTML5 UP](//html5up.net/alpha)",
                 "Developed by [Ajith Cherukad Jose](//github.com/ajithjose)"
                ]
